"""
report_generator.py
Turns an analysis dict (produced by analyzer.analyze_repository) into a
downloadable Markdown report.
"""

from datetime import datetime, timezone


def _bullet_list(items: list[str]) -> str:
    if not items:
        return "- None identified.\n"
    return "\n".join(f"- {item}" for item in items) + "\n"


def _issue_lines(issues: list[dict], category: str) -> str:
    filtered = [i for i in issues if i.get("category") == category]
    if not filtered:
        return "- None identified.\n"
    lines = []
    for issue in filtered:
        severity = issue.get("severity", "low").upper()
        file_ref = issue.get("file", "/")
        lines.append(f"- **[{severity}]** `{file_ref}` — {issue.get('description', '')}")
    return "\n".join(lines) + "\n"


def build_markdown_report(analysis: dict) -> str:
    repo = analysis["repository"]
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    md = f"""# CodeGuardian AI — Engineering Report

**Repository:** {repo['name']}
**Generated:** {generated_at}
**Analysis mode:** {analysis['analysis_mode']}
**Maintainability score:** {analysis['maintainability_score']} / 100

---

## Repository Summary

{analysis['summary']}

| Metric | Value |
|---|---|
| Files analyzed | {repo['file_count']} |
| Lines of code | {repo['total_lines']} |
| Repository size | {repo['total_size_display']} |
| Primary language | {repo['primary_language']} |
| Framework(s) detected | {repo['framework']} |

---

## Architecture Overview

{analysis['architecture_overview']}

---

## Code Quality

{analysis['code_quality']}

### Code quality findings
{_issue_lines(analysis['issues'], 'quality')}

---

## Security Findings

{analysis['security_analysis']}

{_issue_lines(analysis['issues'], 'security')}

---

## Documentation Analysis

{analysis['documentation_analysis']}

{_issue_lines(analysis['issues'], 'documentation')}

---

## Strengths

{_bullet_list(analysis['strengths'])}

---

## AI Suggestions

{_bullet_list(analysis['ai_suggestions'])}

---

## Improvement Roadmap

{_bullet_list(analysis['improvement_roadmap'])}

---

*Generated by CodeGuardian AI.*
"""
    return md
